---
ingress:
  enabled: true
  className: example

allowlist:
  custom-1: "1.1.1.1/32"
  custom-2: "2.2.2.2/32"
  groups:
    - example-group-1
    - example-group-2

allowlist_version: "123-abc"

allowlist_groups:
  example-group-1:
    item-1: "3.0.0.0/32"
    item-2: "4.0.0.0/32"
  example-group-2:
    item-1: "5.0.0.0/32"
    item-2: "6.0.0.0/32"

scheduledDowntime:
  enabled: true

retryDlqCronjob:
  enabled: true

postgresDatabaseRestore:
  enabled: true

env:
  APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

batchjobs:
  - name: my-job
    type: A_TYPE
    schedule: "30 2 * * 1"
    resources:
      requests:
        cpu: 5m
        memory: 500Mi
      limits:
        cpu: 10m
        memory: 1000Mi
  - name: my-job2
    type: A_TYPE
    schedule: "30 2 * * 1"
